name: "Create teams"
description: "Creates empty teams and optionally attach an idp group"
inputs:
  # Auth params
  pat:
    description: "The PAT used to authenticate."
    required: false
  app_id:
    description: "The GitHub App ID used to authenticate."
    required: false
  app_private_key:
    description: "The GitHub App private key used to authenticate."
    required: false
  app_installation_id:
    description: "The GitHub App installation id used to authenticate."
    required: false
  api_url:
    description: "GitHub API url. Change this if using GitHub Enterprise Server."
    required: false
    default: "https://api.github.com"

  enterprise_type:
    description: 'Type of enterprise we are adding teams/groups to. Required for IDP group logic. Can be "cloud", "emu", "server".'
    required: false
    default: "cloud"

  team_visibility:
    description: 'The visibility of the teams being created. Can be "closed", "secret".'
    required: false
    default: "closed"
  org:
    description: "The organization with the team and the repo."
    required: true

  admin_teams:
    description: 'Input groups. Expected form is a string formatted like this: "<GitHub_Team_1_Name>:<Entra_Group_1_Name>,<GGitHub_Team_2_Name>:<Entra_Group_2_Name>..."'
    required: false
  maintain_teams:
    description: 'Input groups. Functionality is identical to "admin_teams", either or both can be set'
    required: false
  write_teams:
    description: 'Input groups. Functionality is identical to "admin_teams", either or both can be set'
    required: false
  triage_teams:
    description: 'Input groups. Functionality is identical to "admin_teams", either or both can be set'
    required: false
  read_teams:
    description: 'Input groups. Functionality is identical to "admin_teams", either or both can be set'
    required: false

runs:
  using: "node20"
  main: "dist/index.js"
